### ISSUE TITLE
New test proposal: CORS policy check pattern

### ISSUE THREAD

**Issue by starbuck3000** [FloeDesignTechnologies/phpcs-security-audit#12]
Hi, 
The scanner fails detecting a line like this:
->withHeader('Access-Control-Allow-Origin', '*')

Suggestion: add a warning for lines containing both patterns "Access-Control-Allow-Origin" and "*" on the same line.

**Comment by jmarcil** [comment]
Hey,

this example look like it's from the Slim Framework, which is unsupported.

As for the suggestion, PHP CodeSniffer works with tokens and not lines, so it would have to be two T_STRING token next together. That would actually cover the case of Slim and Symfony There's also as one string as `header('Access-Control-Allow-Origin: *);` is normal PHP.

Working on implementing something quick..

Thanks for the suggestion!

**Comment by jmarcil** [comment]
Added as a Misc one (and found that I wasn't loading the one rule in Misc):
```
<!-- Misc -->
<rule ref="Security.Misc.BadCorsHeader"/>
<rule ref="Security.Misc.IncludeMismatch"/>
```
