### ISSUE TITLE
Error and Warning for Security.BadFunctions.CallbackFunctions are for WarnFringestuff

### ISSUE THREAD

**Issue by abderrahmaneib** [FloeDesignTechnologies/phpcs-security-audit#19]
Hello,

In the CallbackFunctions sniff, addError and addWarning add ErrFringestuff and WarnFringestuff respectively as arguments.

I think it should be something like WarnCallbackFunctions and ErrCallbackFunctions.

Thank you !

**Comment by abderrahmaneib** [comment]
Same with SQLfunctions sniff: it outputs WarnFilesystem and ErrFilesystem

**Comment by jmarcil** [comment]
Good catch @abderrahmaneib!

I agree with your assertions and naming.

Would you mind opening a PR for those?

Thanks!

**Comment by jmarcil** [comment]
woops hit close too fast, re-open if you can't send a PR!
