### ISSUE TITLE
IncludeMismatchSniff fails to recognize file extensions when require line ends in a semicolon

### ISSUE THREAD

**Issue by Auspicus** [FloeDesignTechnologies/phpcs-security-audit#26]
To reproduce run the sniff over the following:

```php
// Our extension should be picked up as .php
require "required_php_file.php";

/**
 * Instead, the sniff fails to find the extension and we get an error:

 * No file extension has been found in a include/require function.
 * This implies that some PHP code is not scanned by PHPCS.
 */
```

**Comment by jmarcil** [comment]
Sorry but I can't reproduce that actually.

At first your PR made sense.. but then I realized that the regex is OK because it's actually matching over that full string `"required_php_file.php"` it got from `$tokens[$s]['content']`.

Can you create a full .php file for me to test on?

**Comment by jmarcil** [comment]
I can't still repro that bug.

@Auspicus can you validate on your end the issue is not happening anymore?

Thanks!

**Comment by Auspicus** [comment]
Yeah, you can go ahead and close. Not sure how to reproduce either at this point. It's passing on the same code that it failed on before. Maybe another commit had fixed it.

**Comment by jmarcil** [comment]
Thanks for the follow up!
