### ISSUE TITLE
phpStorm: where to add documentation?

### ISSUE THREAD

**Issue by pavarnos** [FloeDesignTechnologies/phpcs-security-audit#29]
The `symlink.sh` is not really needed if you install with composer and install phpcs with composer. 

create a file `phpcs_security.xml` in your project root.
```xml
<?xml version="1.0"?>
<ruleset name="Security" namespace="PHPCS_SecurityAudit">
    <namespace>PHPCS_SecurityAudit</namespace>
    <config name="ParanoiaMode" value="1"/>
    <rule ref="./vendor/pheromone/phpcs-security-audit/Security/Sniffs/BadFunctions"/>
</ruleset>
```

create a file `phpcs.xml` in your project root
```xml
<?xml version="1.0"?>
<ruleset name="PHP_CodeSniffer" >
    <!-- set up your coding standard, and any other configuration you need -->
    <rule ref="PSR12" />
    </rule>

    <!-- include phpcs-security-audit -->
    <rule ref="./phpcs_security.xml"/>
</ruleset>
```

To get it working in phpStorm, follow the instructions here https://www.jetbrains.com/help/phpstorm/using-php-code-sniffer.html and choose a custom coding standard. Select your `phpcs.xml` file.

If I wanted to make a PR to add this somewhere, what is the best place?

**Comment by jmarcil** [comment]
So far everything is in README.md. Make sure you identify correctly that this is for phpStorm.

For the symlink, the steps I stated was the one I had to take to have them work. I'm on Windows so maybe Linux has better results.

Feel free to clear up the docs, you could even make an INSTALL.md file if you want that we link from the README. Like we put one solution (the easiest, most likely to be used) in the README and then the rest in INSTALL.

Thanks for sharing and helping!
