### ISSUE TITLE
Beautify the project

### ISSUE THREAD

**Issue by vladyslavstartsev** [FloeDesignTechnologies/phpcs-security-audit#34]
This is kind of a meta issue that I have came up with
There are some changes that I think should be implemented
It will be very useful if this repo will have tests since it's opensource and a lot of people rely on it (at the moment there is 40k downloads)
- update the required php version to accept at least php7.2. It kind of weird to see the security audit repo do support the outdated php version the EOL if it was `3 Sep 2015`. 
- fix false positives
for example, this piece of code is false positive
```

<?php

class FakeDeleteClass
{
    public function fakeDelete(string $baz): void
    {
        $this->service->delete($baz);
    }
}
```
it says `7 | WARNING | Filesystem function delete() detected with dynamic parameter` which is not true since it's my function not php build in one.
- add tests to not ran into false positives again

Also it (the issue) can be changed since I can come up with new ideas.

But I will not implement any of those without approve from the members if `FloeDesignTechnologies` organisation.

**Comment by jmarcil** [comment]
Hello @vladyslavstartsev,

thanks for your interest in this project!

If you want to do pull requests, be my guess! I'm the main repo maintainer.

The delete() function problem with objects is actually documented in #31, so if you want to contribute by fixing or add on that issue you can certainly do.


For the PHP version, does the tool work on 7.2? The documentation says that it's for `PHP 5.4 or higher`, so 7.2 is covered. I mean the composer file is pretty clear `"php": ">=5.4",`. Please clarify if it's not what you are saying.

**Comment by jmarcil** [comment]
Hi @vladyslavstartsev,

following #70, we now have a way to create unit tests.

If you want to contribute I believe that now is a good time.

We're working on release 3.0 and I want to have better documentation and start to work on lowering false positive.

I'll be closing this as it doesn't have any action items others than the questions I've answered.

Please feel free to send us PR and participate in other discussions.

Thanks.
