### ISSUE TITLE
New release to Packagist?

### ISSUE THREAD

**Issue by l3ku** [FloeDesignTechnologies/phpcs-security-audit#39]
The current newest release of this package was made in February 2018, and there seems to have been some development after that until December 2018. The motivation that made me create this issue was that the Packagist release 2.0.0 does not include the contents of commit https://github.com/FloeDesignTechnologies/phpcs-security-audit/commit/236edfccad6c33e66e33d17338b7abe71a30b86b, which adds support for automatic loading of the sniffs via `phpcodesniffer-composer-installer`. I am pretty sure that this is a feature that also many other Composer users would like to have in their project without having to use the `dev-master` version of the `pheromone/phpcs-security-audit´ package.

**Comment by jmarcil** [comment]
Hello @l3ku,

thanks for looking at this.

I'll do a few changes such as fixing #40 and package a 2.0.1 release that should be published on Packagist then.

**Comment by jmarcil** [comment]
I reconnected Packagist to this repo and created https://github.com/FloeDesignTechnologies/phpcs-security-audit/releases/tag/2.0.1

And there we have:
https://packagist.org/packages/pheromone/phpcs-security-audit#2.0.1

Let me know if I missed something!
