### ISSUE TITLE
Exclude patterns doesnot work inside rules

### ISSUE THREAD

**Issue by webinvader** [FloeDesignTechnologies/phpcs-security-audit#45]
I would like to be able to use the exclude-pattern for specific rules in a ruleset.xml 

```
<rule ref="Security.BadFunctions.FilesystemFunctions">
        <exclude-pattern>*/config/*</exclude-pattern>
</rule>
```
This phpcs functionality does not appear to be working with phpcs-security-audit rules.

**Comment by jrfnl** [comment]
This is caused by this project using a non-standard implementation. See #47 for more information.
