### ISSUE TITLE
PR #50 breaks drupal7 usage

### ISSUE THREAD

**Issue by jmarcil** [FloeDesignTechnologies/phpcs-security-audit#58]
oops didn't test that after PR #50 

when trying example_drupal7_ruleset.xml getting error:
```
ERROR - Invalid CmsFramework value "Drupal7" in config. Must be a class under Security_Sniffs.
```

We just need to change UtilsFactory, I'll get to it in a few minutes.

**Comment by jrfnl** [comment]
Thanks for catching that!
