### ISSUE TITLE
Cannot redeclare class Security_Sniffs_Drupal7_SQLiSniff

### ISSUE THREAD

**Issue by andrewholgate** [FloeDesignTechnologies/phpcs-security-audit#6]
The current dev version produces the following error:

```
PHP Fatal error:  Cannot redeclare class Security_Sniffs_Drupal7_SQLiSniff in pheromone/phpcs-security-audit/Security/Sniffs/Drupal7/SQLiSniff.php on line 4
```

This is caused by the incorrect declaration in:
`pheromone/phpcs-security-audit/Security/Sniffs/Drupal7/AESModuleSniff.php`

**Comment by willc** [comment]
I'm getting this error now:

`PHP Fatal error:  Cannot redeclare class Security_Sniffs_Drupal7_SQLiSniff in /usr/share/php/PHP/CodeSniffer/Standards/Security/Sniffs/Drupal7/AESModuleSniff.php on line 4`
