### ISSUE TITLE
ERROR: Referenced sniff "Security.BadFunctions.Asserts" does not exist

### ISSUE THREAD

**Issue by dimanus** [FloeDesignTechnologies/phpcs-security-audit#80]
./vendor/bin/phpcs --standard=./vendor/pheromone/phpcs-security-audit/example_drupal7_ruleset.xml ./vendor/pheromone/phpcs-security-audit/tests.php
ERROR: Referenced sniff "Security.BadFunctions.Asserts" does not exist

php -v
PHP 7.3.12-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Nov 28 2019 07:37:16) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.12, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.12-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.8.0, Copyright (c) 2002-2019, by Derick Rethans

**Comment by dimanus** [comment]
fixed by 
composer require --dev dealerdirect/phpcodesniffer-composer-installer

**Comment by NM-Fernando** [comment]
> fixed by
> composer require --dev dealerdirect/phpcodesniffer-composer-installer

Thank you so much..it's working
