### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by mzeis** [FloeDesignTechnologies/phpcs-security-audit#9]
Hi,

do you consider to create tags/releases for this repository?

Thanks!

Matthias

**Comment by Webysther** [comment]
We need this fix to use without warnings: https://www.versioneye.com/php/pheromone:phpcs-security-audit/dev-master

**Comment by jmarcil** [comment]
created 1.0.0 https://github.com/FloeDesignTechnologies/phpcs-security-audit/releases/tag/1.0.0
